FROM f5devcentral/f5-api-services-gateway

# Add endpoint to REST container
COPY ./nodejs /var/config/rest/iapps/bigip-blue-green/nodejs
COPY ./node_modules /var/config/rest/iapps/bigip-blue-green/nodejs/node_modules